### ISSUE TITLE
[Question] Running what kind of methods?

### ISSUE THREAD

**Issue by LeLocTai** [stillwwater/command_terminal#1]
In README this is defined as "in-game Console for calling C# methods". I haven't try this, but from the gif as well as the examples, it seem what you mean is calling custom commands? 
IMO "calling C# methods" would suggest you can run arbitrary methods, something like:
`Debug.Log(GetComponent<Camera>().fieldOfView)`

**Comment by stillwwater** [comment]
You can call methods marked with the `[RegisterCommand]` attribute. This is not a run-time C# evaluator.

I can see that wording could imply that this can run arbitrary C# code. What would you suggest to make this clearer in the README?

**Comment by LeLocTai** [comment]
I think the simplest way is to just stop the sentence at "in-game Console". The rest of the file already imply its capabilities.

**Comment by stillwwater** [comment]
I totally agree the introductory sentence is redundant in context with the rest of the file. I've shortened it in `821c220`.

Thanks for the suggestion.
