### ISSUE TITLE
Static methods not called if asset is in the /Plugins/ folder

### ISSUE THREAD

**Issue by Saucy** [stillwwater/command_terminal#2]
Hello!

I'm having trouble having static methods appear in the _help_-command, or being able to run at all if I have Command Terminal-folder in the /Plugins/ folder. Command Terminal works if it is outside the /Plugins/ folder.

My code:

```c#
using CommandTerminal;

public static class DebugTestCommand {
  [RegisterCommand(Help = "Outputs message")]
  static void CommandHello (CommandArg[] args) {
    Terminal.Log("Hello world!");
  }
}
```

**Comment by stillwwater** [comment]
Hi!

The Plugins folder compiles to a separate assembly. Right now the `RegisterCommand` attribute only works in the main assembly [(source)](https://github.com/stillwwater/command_terminal/blob/f063e938baf899ea8d396b39f5774643212979fe/CommandTerminal/CommandShell.cs#L93).

Try registering the command manually using `Terminal.Shell.AddCommand`.

I'll look into supporting separate assemblies.

**Comment by JimmyCushnie** [comment]
I've fixed this issue in [my fork](https://github.com/JimmyCushnie/Command-Terminal-Plus) of Command Terminal. @stillwwater, if you want to do this it's very simple. On line 35 of `CommandShell.cs`, do this:

```
foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies()) {
                foreach (var type in assembly.GetTypes()) {
```

instead of this:

```
foreach (var type in Assembly.GetExecutingAssembly().GetTypes()) {
```
