### ISSUE TITLE
Binding hotkey to F1-F12 doesn't register first letter in input

### ISSUE THREAD

**Issue by Saucy** [stillwwater/command_terminal#3]
I have a Swedish QWERTY keyboard so "\`" doesn't work for me as a hotkey (["§"-key doesn't work](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/KB_Sweden.svg/2000px-KB_Sweden.svg.png) either, but I think that's a limitation from Unity itself. American "`" is positioned at "Ö" on the image I linked).

So I changed the hotkey to "f1" instead. The command terminal works but the first letter isn't registered when typing into the input.

Also: I changed the hotkey to "tab" and it enables the terminal but unable to close it again.

**Comment by stillwwater** [comment]
This is a bug, thanks for pointing it out! Fixed in `081406c`.

Edit: To your second comment, "tab" won't work as it's used as a hotkey for the autocomplete.

**Comment by Saucy** [comment]
Awesome work! Good to know. 👍
